
image: xenia-apache2-php5.6-fpm-percona

before_script:
  - apt-get install vim nano
  - cp ./vhost_template.conf.tpl /etc/apache2/sites-available/
  - cp ./template.conf.tpl /etc/php/5.6/fpm/pool.d/
  - service mysql start
  - service apache2 start
  - service php5.6-fpm start 

test:
  script: 
  - ./addNewSftp -d testdb -u test -p test.example.com
  - mysql -e "show databases;"
  - id test
  - cat /etc/apache2/sites-enabled/vhost_test.example.com.conf
  - cat /etc/php/5.6/fpm/pool.d/test.example.com.conf
  - ls -l /var/www/test/*
